name: Test
  
# 控制何时运行此操作。当通过UI或API手动触发时，工作流将运行。  

on: [workflow_dispatch]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login docker hub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      # 指定login命令登录hub.docker.com，帐号和密码已经在GitHub网页中配置好了
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
