name: Test
  
# 控制何时运行此操作。当通过UI或API手动触发时，工作流将运行。  

on: [workflow_dispatch]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"
          echo "DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN=${{ vars.DOCKERHUB_TOKEN }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}
